### ISSUE TITLE
Add ATT&CK and Vulnerability info to `external_references`

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/txt2detection#37]
Should include any linked info in `external_references` of correct Indicator for rule in addition to relationships generated as follows

```
        {
            "source_name": "mitre-attack",
            "external_id": "tactic",
            "description": "<SIGMA RULE TAG ATT&CK TACTIC [N]>"
        },
        {
            "source_name": "mitre-attack",
            "external_id": "technique",
            "description": "<SIGMA RULE TAG ATT&CK TECHNIQUE [N]>"
        },
        {
            "source_name": "mitre-attack",
            "external_id": "technique",
            "description": "<SIGMA RULE TAG ATT&CK TECHNIQUE [N]>"
        },
        {
            "source_name": "cve",
            "external_id": "<SIGMA RULE CVE TAG [N]>",
            "description": "https://nvd.nist.gov/vuln/detail/<SIGMA RULE CVE TAG [N]>",
        }
```

**Comment by himynamesdave** [comment]
@fqrious not sure if related to #32 but see following.

Indicator `external_references` is blank

[bundle.json](https://github.com/user-attachments/files/19552145/bundle.json)

```
id: 4116959e-ad15-56b3-b356-f2f4d78c5dfe
title: Detection of CVE-2024-56520 Exploitation in Progress Kemp LoadMaster
description: This rule detects potential exploitation attempts of CVE-2024-56520,
    an unauthenticated command injection vulnerability in Progress Kemp LoadMaster.
    It identifies suspicious GET requests to the '/access/set' API with specific parameters
    and an unusual Authorization header.
detection:
    condition: selection
    selection:
        http_method: GET
        url_path: /access/set
        parameters:
            param: enableapi
            value: '1'
        headers:
            Authorization: '*'
logsource:
    category: webserver
    product: Progress Kemp LoadMaster
falsepositives:
- Legitimate administrative actions using the '/access/set' API with the same parameters.
- Testing or scanning activities by security teams.
tags:
- attack.t1547
- attack.t1190
- cve.2024-56520
- txt2detection.label1
- txt2detection.label2
confidence: 85
status: experimental
license: Apache-2.0
references:
- https://github.com/muchdogesec/txt2detection/
```
