### ISSUE TITLE
For all lists, ensure correct indentation

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/txt2detection#60]
```
detection:
    condition: selection
    selection:
        http_method: GET
        url_path: /access/set
        parameters:
            param: enableapi
            value: '1'
        headers:
            Authorization: base64_uncommon_character
logsource:
    product: webserver
    service: http
falsepositives:
- Legitimate administrative actions using the '/access/set' API with the specified
    parameters.
- Authorized API calls with unusual base64 encoded values in the 'Authorization' header.
tags:
- tlp.red
- attack.t1547
- attack.t1190
- cve.2024-56520
```

should be 

```
detection:
    condition: selection
    selection:
        http_method: GET
        url_path: /access/set
        parameters:
            param: enableapi
            value: '1'
        headers:
            Authorization: base64_uncommon_character
logsource:
    product: webserver
    service: http
falsepositives:
    - Legitimate administrative actions using the '/access/set' API with the specified
    parameters.
    - Authorized API calls with unusual base64 encoded values in the 'Authorization' header.
tags:
    - tlp.red
    - attack.t1547
    - attack.t1190
    - cve.2024-56520
```
