### ISSUE TITLE
On sigma rule upload mode indicator and report uuids should match rule

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/txt2detection#75]
## 1

This is different behaviour to ai mode where Indicator is random (b/c one report can have many rules)

In the case of Sigma upload, Report and Indicator have 1:1 relationship so we can use the same ID

## 2

If `report_id` passed, this should be used as rule id

## relevant docs

Note, input rules don't always have an `id` it is not required by the Sigma spec

As such;

1. if no ID in rule, one will be autogenerated using a random UUIDv4 and added to the rule
2. if ID passed in rule or via CLI, the following logic will apply...

To reduce the risk of future collisions, the rule is renamed with a new ID, and the following is written into the rule;

```
id: <REPORT ID IN CLI, ELSE NEW RANDOMLY GENERATED UUID V4>
related:
  - id: <OLD ID>
    type: renamed
```

This ensures the original ID of the rule can retrieved if needed.
