### ISSUE TITLE
Special labels failing in AI mode / Sigma Upload

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/txt2detection#78]
Allowed `a-z`, `0-9`. Must use a namespaces (`NAMESPACE.TAG_VALUE`). e.g.`"namespace.label1","namespace.label_2"` would create 2 labels. Added to both report and indicator objects created and the rule `tags`.
  * note: you can use reserved namespaces `cve.` and `attack.` when creating labels to perform external enrichment using Vulmatch and CTI Butler. All Indicators will be linked to these objects (AI enrichments link individual rules). Created tags will be appended to the list of AI generated tags.
  * note: you cannot use the namespace `tlp.` Use the `--tlp_level` flag instead.

## Tests

Should fail because disallowed tag

```shell
python3 txt2detection.py \
  --input_file tests/files/CVE-2024-56520.txt \
  --name "Disallowed tag" \
  --ai_provider openai:gpt-4o \
  --labels "tlp.red" \
  --report_id a6f2aaff-4e33-4280-bb01-ab1bd3b95362
```

Should have cve tag and matching vulnerability object

```shell
python3 txt2detection.py \
  --input_file tests/files/CVE-2024-56520.txt \
  --name "Disallowed tag" \
  --ai_provider openai:gpt-4o \
  --labels "cve.2025-3593" \
  --report_id fab3707e-00fc-4f35-9d6d-e72dc0b6ba08
```

Should have attack tags and matching attack pattern and x-mitre-tactic objects

```shell
python3 txt2detection.py \
  --input_file tests/files/CVE-2024-56520.txt \
  --name "Disallowed tag" \
  --ai_provider openai:gpt-4o \
  --labels "attack.t1071.001","attack.command_and_control" \
  --report_id 940e8807-381e-41df-a27e-08914bafd93c
```

**Comment by himynamesdave** [comment]
@fqrious cve and attack special label tests both fail

```txt2detection.py: error: argument --labels: Unsupported tag namespace `cve````

**Comment by fqrious** [comment]
Note: I have updated `--labels` to not be comma separated, they are now space-separated nargs like `--external_refs` and `--reference_urls`

so, `--labels cve.2024-0101 attack.supply-chain` instead of `--labels cve.2024-0101,attack.supply-chain`

**Comment by himynamesdave** [comment]
@fqrious 

## CVE Failing


Should have cve tag and matching vulnerability object

```shell
python3 txt2detection.py \
  --input_file tests/files/CVE-2024-56520.txt \
  --name "CVE tags" \
  --ai_provider openai:gpt-4o \
  --labels "cve.2025-3593" \
  --report_id fab3707e-00fc-4f35-9d6d-e72dc0b6ba08
```

rule looks like this 

```
id: 59d33e8e-2317-47f5-9c9a-87dfd7e1a878
title: Detection of CVE-2024-56520 Exploitation in Progress Kemp LoadMaster
description: This rule detects potential exploitation attempts of CVE-2024-56520,
    an unauthenticated command injection vulnerability in Progress Kemp LoadMaster.
    It identifies suspicious GET requests to the '/access/set' API with specific parameters
    and an unusual 'Authorization' header.
detection:
    condition: selection
    selection:
        http_method: GET
        url_path: /access/set
        parameters:
            param: enableapi
            value: '1'
        headers:
            Authorization: base64_uncommon_character
logsource:
    category: webserver
    product: Progress Kemp LoadMaster
status: experimental
falsepositives:
- Legitimate administrative actions using the '/access/set' API with similar parameters.
- Testing or scanning activities by security teams.
tags:
- attack.t1547
- attack.t1190
- cve.2024-56520
- tlp.clear
- cve.2025-3593
level: high
date: 2025-04-20
modified: 2025-04-20
author: identity--a4d70b75-6f4a-5d19-9137-da863edd33d7
```

but only Vulnerability for `cve.2024-56520` (AI generated) exists in the bundle.

Also no CVE `external_references` for it in Indicator

## ATT&CK

```
python3 txt2detection.py \
  --input_file tests/files/CVE-2024-56520.txt \
  --name "ATT&CK tags tag" \
  --ai_provider openai:gpt-4o \
  --labels "attack.t1071.001" "attack.command-and-control" \
  --report_id 940e8807-381e-41df-a27e-08914bafd93c
```

creates rule

```
id: b71988ce-22b3-4062-adfe-e7105ff6d99b
title: Detection of CVE-2024-56520 Exploitation in Progress Kemp LoadMaster
description: This rule detects potential exploitation attempts of CVE-2024-56520,
    an unauthenticated command injection vulnerability in Progress Kemp LoadMaster.
    It identifies suspicious GET requests to the '/access/set' API with specific parameters
    and an unusual 'Authorization' header.
detection:
    condition: selection
    selection:
        http_method: GET
        url_path: /access/set
        parameters:
            param: enableapi
            value: '1'
        headers:
            Authorization: '*'
logsource:
    category: webserver
    product: Progress Kemp LoadMaster
status: experimental
falsepositives:
- Legitimate administrative actions using the '/access/set' API with similar parameters.
- Non-malicious use of base64 encoded 'Authorization' headers with uncommon characters.
tags:
- attack.t1547
- attack.t1190
- cve.2024-56520
- tlp.clear
- attack.t1071.001
- attack.command-and-control
level: high
date: 2025-04-20
modified: 2025-04-20
author: identity--a4d70b75-6f4a-5d19-9137-da863edd33d7
```

Same behaviour as CVE, no lookup/import of manually added objects

Also no ATT&C `external_references` for it in Indicator

**Comment by himynamesdave** [comment]
@fqrious do these tests work for you? i still don't see the tags or external lookups

```
python3 txt2detection.py \
  --input_file tests/files/CVE-2024-56520.txt \
  --name "CVE tags" \
  --ai_provider openai:gpt-4o \
  --labels "cve.2025-3593" \
  --report_id fab3707e-00fc-4f35-9d6d-e72dc0b6ba08
```

still gives

```
id: 582f8cce-fdf5-44ea-8cd1-2b21aceef3f9
title: Detection of CVE-2024-56520 Exploitation in Progress Kemp LoadMaster
description: This rule detects potential exploitation attempts of CVE-2024-56520,
    an unauthenticated command injection vulnerability in Progress Kemp LoadMaster.
    It identifies suspicious GET requests to the '/access/set' API with specific parameters
    and an unusual 'Authorization' header.
detection:
    condition: selection
    selection:
        http_method: GET
        url_path: /access/set
        parameters:
            param: enableapi
            value: '1'
        headers:
            Authorization: base64_uncommon_character
logsource:
    category: webserver
    product: Progress Kemp LoadMaster
status: experimental
falsepositives:
- Legitimate administrative actions using the '/access/set' API with the same parameters.
- Base64 encoded 'Authorization' headers that include uncommon characters for legitimate
    reasons.
tags:
- attack.t1547
- attack.t1190
- cve.2024-56520
- tlp.clear
level: high
date: 2025-04-21
modified: 2025-04-21
author: identity--a4d70b75-6f4a-5d19-9137-da863edd33d7

```
